### ISSUE TITLE
Unable to import module due to qtrac.aaset module name

### ISSUE THREAD

**Issue by tirithen** [mark-summerfield/aaset#1]
The module declaration does not match the package name and this makes it hard to compile the package with dub.

The module name (https://github.com/mark-summerfield/aaset/blob/master/src/aaset.d#L18) shuold probably be aaset instead of qtrac.aaset?

**Comment by mark-summerfield** [comment]
I import it into several projects all of which use dub. Here's an extract from one such project's dub.json:
```
	"dependencies": {
		"aaset": "~>0.2.2",
		"gtk-d:gtkd": "~>3.9.0"
	},
```

And in a D file I write:

```D
import aaset: AAset;
```
Hope this helps.
